version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    restart: on-failure
#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "3000:80"
#    depends_on:
#      - node
